spring.application.name=ticket-api

server.port=8082

app.user.default.roles=ROLE_USER,ROLE_GUEST,ROLE_VIEWER

# Configurações JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Configuração para usar banco de dados SQLite:
spring.datasource.url=jdbc:sqlite:db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.sql.init.mode=always