
### Realizar Notificação

POST /api/v1/evidences HTTP/1.1
Host: localhost:8083
Content-Type: multipart/form-data; boundary=upload

--upload
Content-Disposition: form-data; name=evidence; filename=teste.jpg
Content-Type: image/jpg

< ./cat.jpg
--upload---